project:
  type: website
  output-dir: docs

website:
  title: "VM0010 Starter Template"
  navbar:
    left:
      - href: VM0010-starter-template.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

