project:
  type: website
  output-dir: docs

website:
  title: "Allometry Validation"
  navbar:
    left:
      - href: allometric-model-validation.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

